version: "3.7"
services:
  app:
    build:
      args:
        user: user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: docker-test
    container_name: docker-test-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - docker-test

  db:
    image: mysql:5.7
    container_name: docker-test-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./:/docker-entrypoint-initdb.d
    networks:
      - docker-test

  nginx:
    image: nginx:alpine
    container_name: docker-test-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./:/etc/nginx/conf.d/

    networks:
      - docker-test

networks:
  docker-test:
    driver: bridge
    